---
- name: Open the firewall for prometheus
  hosts: homelab_nodes
  become: yes
  tasks:
    - ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        state: enabled
        immediate: true

- name: Install and run Prometheus Node Exporter on homelab nodes
  hosts: homelab_nodes
  become: yes
  roles:
    - role: prometheus.prometheus.node_exporter
      vars:
        node_exporter_web_listen_address: "0.0.0.0:9100"
